// src/store/actionTypes.js
export const SET_LENGTH = 'SET_LENGTH';
export const SET_WIDTH = 'SET_WIDTH';
export const SET_ROOF_TYPE = 'SET_ROOF_TYPE';
export const SET_TOTAL_AREA = 'SET_TOTAL_AREA';
export const SET_SELECTED_PRODUCTS = 'SET_SELECTED_PRODUCTS';
export const SET_OVERALL_TOTAL = 'SET_OVERALL_TOTAL';
export const SET_TOTAL_SAVINGS = 'SET_TOTAL_SAVINGS';
export const SET_DISCOUNTED_PRICE = 'SET_DISCOUNTED_PRICE';
export const SET_RECOMMENDED_VARIANT = 'SET_RECOMMENDED_VARIANT';
export const SET_BUCKETS_NEEDED = 'SET_BUCKETS_NEEDED';
export const SET_SUBTOTAL = 'SET_SUBTOTAL';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const DESELECT_PRODUCT = 'DESELECT_PRODUCT';
export const OPEN_POPUP = 'OPEN_POPUP';
export const CLOSE_POPUP = 'CLOSE_POPUP';
export const UPDATE_BUCKETS_NEEDED = 'UPDATE_BUCKETS_NEEDED';
export const UPDATE_VARIANT = 'UPDATE_VARIANT';